# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`, `strawberry`.

theme = "ocean"
# Enable users to switch between day and night mode?
day_night = true

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
font = ""


font_size = "L"


############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization

site_type = "Person"

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = "This website is about research in Monoidal Category Theory, Quantum Computing, Linear Logic and how these wonderful subject can fit in the same picture."

############################
## Site Features
############################

# Enable source code highlighting? true/false
# Documentation: https://wowchemy.com/docs/writing-markdown-latex/#highlighting-options
highlight = true
highlight_languages = ["r"]  # Add support for highlighting additional languages
highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = true

# Enable diagram rendering? true/false
#   If false, you can enable diagrams on a per page basis as needed.
diagram = true

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = true

# Enable visitors to edit pages?
#   `repo` defines the repository URL. `editable` defines which page types can be edited.
edit_page = {repo_url = "", content_dir = "", repo_branch = "main", editable = {page = false, post = false, book = false}}

# Show related content at the bottom of pages?
show_related = {book = true, page = false, post = true, project = true, publication = true, talk = true}

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-gb"

############################
## Contact details
##
## These details power the Contact widget (if enabled).
## Additionally, for organizations, these details may be used to enrich search engine results.
############################

# Enter contact details (optional). To hide a field, clear it to "".
email = "n.blanco@pgr.bham.ac.uk"
phone = ""

# Address
# For country_code, use the 2-letter ISO code (see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 )
address = {street = "School Of Computer Science, University of Birmingham", city = "Birmingham", region = "West Midlands", postcode = "B15 2TT", country = "United Kingdom", country_code = "UK"}

# Geographic coordinates
# To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
#coordinates = {latitude = "37.4275", longitude = "-122.1697"}

# Directions for visitors to locate you.
directions = "Office 218"

# Office hours: use `<br>` to insert a line break, or set to "" to remove office hours
office_hours = []

# Enter an optional link for booking appointments (e.g. calendly.com).
appointment_url = ""

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links = [
  {icon = "twitter", icon_pack = "fab", name = "star_autonomy", link = "https://twitter.com/Twitter"},
#  {icon = "skype", icon_pack = "fab", name = "Skype Me", link = "skype:echo123?call"},
#  {icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
#  {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  # {icon = "telegram", icon_pack = "fab", name = "Telegram Me", link = "https://telegram.me/@Telegram"},
  ]

############################
## Social
############################

# Default image for social sharing and search engines. Place image in `static/media/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter = "star_autonomy"

# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

############################
## Regional Settings
############################

# Date and time format (refer to https://wowchemy.com/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Mon, 02 Jan 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "15:04 MST"

# Address format (en-us, en-gb, de, fr-fr, zh).
address_format = "en-gb"

############################
## Advanced
############################

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {enable = true, align = "l", show_logo = true, highlight_active_link = true, show_language = false, show_day_night = true, show_search = true}

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Show a copyright license from creativecommons.org in the site footer?
# Page specific copyright licenses are also possible by adding this option to a page's front matter.
copyright_license = {enable = false, allow_derivatives = false, share_alike = true, allow_commercial = false, notice = "This work is licensed under {license}"}

# Abstract length (characters) in the Compact and Portfolio Card list views. Also, see `summaryLength` in `config.toml`.
abstract_length = 135

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js  = []

# Avatars.
# An avatar is an image that appears next to a user's name.
# An avatar can be uploaded as an image named `avatar` to each user's profile or fetched from Gravatar.com.
[avatar]
  # Get user avatars from Gravatar.com? (true/false)
  gravatar = false

  # Choose a shape for avatar images. Options: circle, square.
  shape = "circle"

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "January 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2

# Breadcrumb navigation
[breadcrumb]
  page_types = {book = true}

############################
## Comments
############################
[comments]
  # Comment provider:
  #   "": Disabled
  #   "disqus": Disqus (https://disqus.com)
  #   "commento": Commento (https://commento.io)
  provider = ""

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = true, project = true, publication = true, talk = true}

  # Configuration of Disqus.
  [comments.disqus]
    shortname = ""  # Paste the shortname from your Disqus dashboard.
    show_count = true  # Show comment count in page header? (true/false)

  # Configuration of Commento.
  [comments.commento]
    # If self-hosting Commento, enter its URL here (e.g. "https://commento.?.com"), otherwise leave empty.
    url = ""

############################
## Search
############################
[search]
  # Search provider:
  #   "": No search engine
  #   "wowchemy": Built-in search engine
  #   "algolia": Algolia (https://www.algolia.com)
  provider = "wowchemy"

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    app_id = ""
    api_key = ""
    index_name = ""
    show_logo = false

############################
## Maps
############################

[map]
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   "": No map
  #   "google": Google Maps
  #   "mapnik": OpenStreetMap (Mapnik)
  #   "mapbox": OpenStreetMap (Mapbox)
  provider = ""
  api_key = ""
  zoom = 15

############################
## Marketing
############################
[marketing]
  google_analytics = "UA-147424188-1"
  google_tag_manager = ""
  google_site_verification = ""

############################
## Content Management System
############################
[cms]
  branch = "master"
  local_backend = false

############################
## Icon Pack Extensions
############################
[icon.pack]
  ai = true  # Academicons icon pack https://jpswalsh.github.io/academicons/

